FIX: Contact page label change in dropdown.
singnet/snet-converter-dapp pull request #165
Opened 2022-04-27 05:23 UTC by Shyam-Khokhariya

2022-04-27 05:27 UTC, Karthi96 approved these changes

2022-04-28 07:53 UTC, rajeevbbqq commented on src/pages/Contact/index.jsx
> +              <SnetContactInput id="bug" fullWidth value={type} onChange={handleTypeChange} label="Category" select options={ContactSupportTypeOptions} />
pass label value as `contactSupportType.CATEGORY` <-- like this

2022-04-28 07:55 UTC, rajeevbbqq requested changes
Please see comments

2022-04-28 08:53 UTC, rajeevbbqq approved these changes

2022-04-28 08:53 UTC, merged